# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170713_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='phone_verification_code',
            field=models.TextField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'Sms'), ('webhook', 'Webhook'), ('hipchat', 'HipChat'), ('slack', 'Slack'), ('pd', 'PagerDuty'), ('po', 'Pushover'), ('pushbullet', 'Pushbullet'), ('opsgenie', 'OpsGenie'), ('victorops', 'VictorOps'), ('discord', 'Discord')], max_length=20),
        ),
    ]
