# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-28 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170713_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='nag_time',
            field=models.DurationField(default=datetime.timedelta(1)),
        ),
        migrations.AddField(
            model_name='check',
            name='nagging',
            field=models.BooleanField(default=False),
        ),
    ]
