# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20170728_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='down_alert',
            field=models.BooleanField(default=False),
        ),
    ]
