# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-07 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20170807_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='phone_verification_code',
            new_name='phone_code',
        ),
    ]
