# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-31 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_check_down_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='down_alert',
        ),
    ]
