# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20170801_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='check_status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('nag', 'Nag')], default='new', max_length=6),
        ),
    ]
