# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-01 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_check_check_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='check_status',
        ),
    ]
