# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-15 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20170814_1224'),
        ('api', '0034_remove_check_check_status'),
    ]

    operations = [
    ]
